ec2_instance:
    instance_id: ['YOUR INSTANCE ID']
    region_id: 'YOUR REGION ID'
    access_key: 'YOUR ACCESS KEY'
    secret_access_key: 'YOUR SECRET ACCESS KEY'
    ec2_user: 'SSH USERNAME'
ssh:
    keyfile: 'KEY FILE NAME'
mc:
    xms: 'MIN GIGS'
    xmx: 'MAX GIGS'